# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aimat.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import *
from PyQt4.QtCore import *
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import cpm_run
import sintering_run

DATASET = "data/single_crystals.csv"

def load_data(dataset):
        return pd.read_csv(dataset)
#single crystals dataframe
SC_DF = load_data(DATASET)

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    # def __inti__(self):
    #     super(Ui_MainWindow, self).__init__()
    #     self.saved_once = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(917, 668)
        QtGui.QApplication.setStyle(QtGui.QStyleFactory.create('plastique'))
        #to find if the file is saved or not
        self.saved_once = 0
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.QuitBtn = QtGui.QPushButton(self.centralwidget)
        self.QuitBtn.clicked.connect(self.quit_application)
        self.QuitBtn.setGeometry(QtCore.QRect(430, 550, 131, 41))
        self.QuitBtn.setObjectName(_fromUtf8("QuitBtn"))
        self.antImg = QtGui.QLabel(self.centralwidget)
        self.antImg.setGeometry(QtCore.QRect(710, 560, 201, 61))
        self.antImg.setObjectName(_fromUtf8("antImg"))
        self.comboBox1 = QtGui.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(230, 140, 176, 27))
        self.comboBox1.setObjectName(_fromUtf8("comboBox1"))
        self.comboBox1.setEditable(True)
        self.comboBox1.setMaxVisibleItems(10)
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox2.setGeometry(QtCore.QRect(230, 220, 176, 27))
        self.comboBox2.setObjectName(_fromUtf8("comboBox2"))
        self.comboBox2.setEditable(True)
        self.comboBox2.setMaxVisibleItems(10)
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 921, 21))
        self.line.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);"))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.diConst1 = QtGui.QTextEdit(self.centralwidget)
        self.diConst1.setGeometry(QtCore.QRect(440, 140, 111, 31))
        self.diConst1.setObjectName(_fromUtf8("diConst1"))
        self.diConst1.setReadOnly(1)
        self.CompLbl = QtGui.QLabel(self.centralwidget)
        self.CompLbl.setGeometry(QtCore.QRect(30, 80, 400, 31))
        self.CompLbl.setObjectName(_fromUtf8("CompLbl"))
        self.Mat1Lbl = QtGui.QLabel(self.centralwidget)
        self.Mat1Lbl.setGeometry(QtCore.QRect(30, 140, 201, 31))
        self.Mat1Lbl.setObjectName(_fromUtf8("Mat1Lbl"))
        self.Mat2Lbl = QtGui.QLabel(self.centralwidget)
        self.Mat2Lbl.setGeometry(QtCore.QRect(30, 220, 201, 31))
        self.Mat2Lbl.setObjectName(_fromUtf8("Mat2Lbl"))
        self.MolarFracLbl = QtGui.QLabel(self.centralwidget)
        self.MolarFracLbl.setGeometry(QtCore.QRect(30, 270, 201, 31))
        self.MolarFracLbl.setObjectName(_fromUtf8("MolarFracLbl"))
        self.molarFrac = QtGui.QTextEdit(self.centralwidget)
        self.molarFrac.setGeometry(QtCore.QRect(230, 270, 111, 31))
        self.molarFrac.setObjectName(_fromUtf8("molarFrac"))
        self.aimatImg = QtGui.QLabel(self.centralwidget)
        self.aimatImg.setGeometry(QtCore.QRect(320, 0, 251, 81))
        self.aimatImg.setObjectName(_fromUtf8("aimatImg"))
        self.diConstLbl = QtGui.QLabel(self.centralwidget)
        self.diConstLbl.setGeometry(QtCore.QRect(430, 100, 141, 17))
        self.diConstLbl.setObjectName(_fromUtf8("diConstLbl"))
        self.Qf1 = QtGui.QTextEdit(self.centralwidget)
        self.Qf1.setGeometry(QtCore.QRect(610, 140, 111, 31))
        self.Qf1.setObjectName(_fromUtf8("Qf1"))
        self.Qf1.setReadOnly(1)
        self.Tcf1 = QtGui.QTextEdit(self.centralwidget)
        self.Tcf1.setGeometry(QtCore.QRect(780, 140, 111, 31))
        self.Tcf1.setObjectName(_fromUtf8("Tcf1"))
        self.Tcf1.setReadOnly(1)
        self.QfLbl = QtGui.QLabel(self.centralwidget)
        self.QfLbl.setGeometry(QtCore.QRect(630, 100, 71, 17))
        self.QfLbl.setObjectName(_fromUtf8("QfLbl"))
        self.TcfLbl = QtGui.QLabel(self.centralwidget)
        self.TcfLbl.setGeometry(QtCore.QRect(790, 100, 101, 17))
        self.TcfLbl.setObjectName(_fromUtf8("TcfLbl"))
        self.diConst2 = QtGui.QTextEdit(self.centralwidget)
        self.diConst2.setGeometry(QtCore.QRect(440, 220, 111, 31))
        self.diConst2.setObjectName(_fromUtf8("diConst2"))
        self.diConst2.setReadOnly(1)
        self.Qf2 = QtGui.QTextEdit(self.centralwidget)
        self.Qf2.setGeometry(QtCore.QRect(610, 220, 111, 31))
        self.Qf2.setObjectName(_fromUtf8("Qf2"))
        self.Qf2.setReadOnly(1)
        self.Tcf2 = QtGui.QTextEdit(self.centralwidget)
        self.Tcf2.setGeometry(QtCore.QRect(780, 220, 111, 31))
        self.Tcf2.setObjectName(_fromUtf8("Tcf2"))
        self.Tcf2.setReadOnly(1)
        self.predictionsLbl = QtGui.QLabel(self.centralwidget)
        self.predictionsLbl.setGeometry(QtCore.QRect(170, 400, 241, 51))
        self.predictionsLbl.setObjectName(_fromUtf8("predictionsLbl"))
        self.diConstPred = QtGui.QTextEdit(self.centralwidget)
        self.diConstPred.setGeometry(QtCore.QRect(440, 410, 111, 31))
        self.diConstPred.setObjectName(_fromUtf8("diConstPred"))
        self.diConstPred.setReadOnly(1)
        self.QfPred = QtGui.QTextEdit(self.centralwidget)
        self.QfPred.setGeometry(QtCore.QRect(610, 410, 111, 31))
        self.QfPred.setObjectName(_fromUtf8("QfPred"))
        self.QfPred.setReadOnly(1)
        self.TcfPred = QtGui.QTextEdit(self.centralwidget)
        self.TcfPred.setGeometry(QtCore.QRect(780, 410, 111, 31))
        self.TcfPred.setObjectName(_fromUtf8("TcfPred"))
        self.TcfPred.setReadOnly(1)
        self.calculateBtn = QtGui.QPushButton(self.centralwidget)
        self.calculateBtn.clicked.connect(self.calculate)
        self.calculateBtn.setGeometry(QtCore.QRect(230, 330, 176, 51))
        self.calculateBtn.setObjectName(_fromUtf8("calculateBtn"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 390, 921, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 430, 921, 41))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.sintLbl = QtGui.QLabel(self.centralwidget)
        self.sintLbl.setGeometry(QtCore.QRect(150, 470, 241, 71))
        self.sintLbl.setObjectName(_fromUtf8("sintLbl"))
        self.colon = QtGui.QLabel(self.centralwidget)
        self.colon.setGeometry(QtCore.QRect(400, 470, 20, 61))
        self.colon.setObjectName(_fromUtf8("colon"))
        self.sintPred = QtGui.QTextEdit(self.centralwidget)
        self.sintPred.setGeometry(QtCore.QRect(440, 490, 111, 31))
        self.sintPred.setObjectName(_fromUtf8("sintPred"))
        self.sintPred.setReadOnly(1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setShortcut('ctrl+N')
        self.actionNew.setStatusTip('New Application')
        self.actionNew.triggered.connect(self.new_application)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setShortcut('ctrl+O')
        self.actionOpen.setStatusTip('Open Application')
        self.actionOpen.triggered.connect(self.open_application)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setShortcut('ctrl+S')
        self.actionSave.setStatusTip('Save the Results')
        self.actionSave.triggered.connect(self.save_application)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        # self.actionSave_As.setShortcut('ctrl+Q')
        # self.actionQuit.setStatusTip('Leave The App')
        self.actionSave_As.triggered.connect(self.save_as_application)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setShortcut('ctrl+Q')
        self.actionQuit.setStatusTip('Leave The App')
        self.actionQuit.triggered.connect(self.quit_application)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setShortcut('ctrl+Z')
        self.actionUndo.setStatusTip('Undo Operation')
        self.actionUndo.triggered.connect(self.undo_application)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setShortcut('ctrl+Y')
        self.actionRedo.setStatusTip('Redo operation')
        self.actionRedo.triggered.connect(self.redo_application)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setShortcut('ctrl+X')
        self.actionCut.setStatusTip('Cut selected')
        self.actionCut.triggered.connect(self.cut_application)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setShortcut('ctrl+C')
        self.actionCopy.setStatusTip('Copy selected')
        self.actionCopy.triggered.connect(self.copy_application)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setShortcut('ctrl+V')
        self.actionPaste.setStatusTip('Paste')
        self.actionPaste.triggered.connect(self.paste_application)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionDelete = QtGui.QAction(MainWindow)
        # self.actionDelete.setShortcut('ctrl+Q')
        self.actionDelete.setStatusTip('Delete')
        self.actionDelete.triggered.connect(self.delete_application)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionReset_All = QtGui.QAction(MainWindow)
        self.actionReset_All.setShortcut('F1')
        self.actionReset_All.setStatusTip('Reset all data to default')
        self.actionReset_All.triggered.connect(self.reset_application)
        self.actionReset_All.setObjectName(_fromUtf8("actionReset_All"))
        self.actionView_Database = QtGui.QAction(MainWindow)
        # self.actionView_Database.setShortcut('ctrl+Q')
        self.actionView_Database.setStatusTip('Show full dataset')
        self.actionView_Database.triggered.connect(self.view_database_application)
        self.actionView_Database.setObjectName(_fromUtf8("actionView_Database"))
        self.actionAI_Model = QtGui.QAction(MainWindow)
        # self.actionAI_Model.setShortcut('ctrl+Q')
        self.actionAI_Model.setStatusTip('Show AI model')
        self.actionAI_Model.triggered.connect(self.aimodel_application)
        self.actionAI_Model.setObjectName(_fromUtf8("actionAI_Model"))
        self.actionPlot = QtGui.QAction(MainWindow)
        self.actionPlot.setShortcut('ctrl+P')
        self.actionPlot.setStatusTip('Plot data')
        self.actionPlot.triggered.connect(self.plot_application)
        self.actionPlot.setObjectName(_fromUtf8("actionPlot"))
        self.actionMinimize = QtGui.QAction(MainWindow)
        self.actionMinimize.setShortcut('ctrl+M')
        self.actionMinimize.setStatusTip('Minimize')
        self.actionMinimize.triggered.connect(self.minimize_application)
        self.actionMinimize.setObjectName(_fromUtf8("actionMinimize"))
        self.actionMaximize = QtGui.QAction(MainWindow)
        # self.actionMaximize.setShortcut('ctrl+M')
        self.actionMaximize.setStatusTip('Maximize')
        self.actionMaximize.triggered.connect(self.maximize_application)
        self.actionMaximize.setObjectName(_fromUtf8("actionMaximize"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        # self.actionDocumentation.setShortcut('ctrl+Q')
        self.actionDocumentation.setStatusTip('Open the documentation')
        self.actionDocumentation.triggered.connect(self.documentation_application)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionSupport = QtGui.QAction(MainWindow)
        # self.actionSupport.setShortcut('ctrl+Q')
        self.actionSupport.setStatusTip('Online support')
        self.actionSupport.triggered.connect(self.support_application)
        self.actionSupport.setObjectName(_fromUtf8("actionSupport"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionReset_All)
        self.menuView.addAction(self.actionView_Database)
        self.menuView.addAction(self.actionAI_Model)
        self.menuView.addAction(self.actionPlot)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionMaximize)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionSupport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        #toolBar actions
        self.closeAction = QtGui.QAction(QtGui.QIcon('images/closebtn.png'), 'Close', self)
        self.closeAction.triggered.connect(self.quit_application)

        self.saveAction = QtGui.QAction(QtGui.QIcon('images/savebtn.png'), 'Save', self)
        self.saveAction.triggered.connect(self.save_application)
        self.downloadAction = QtGui.QAction(QtGui.QIcon('images/downloadbtn.png'), 'Download Results', self)
        self.fontAction = QtGui.QAction(QtGui.QIcon('images/fontbtn.png'), 'Fonts', self)
        #Adding toolbar
        self.toolBar = QtGui.QToolBar(MainWindow)
        # self.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.toolBar.setGeometry(QtCore.QRect(0, 30, 917, 40))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        # self.toolBar = self.addToolBar('close')
        # self.toolBar.setNativeToolBar(False)
        self.toolBar.addAction(self.closeAction)
        self.toolBar.addAction(self.saveAction)
        self.toolBar.addAction(self.downloadAction)
        self.toolBar.addAction(self.fontAction)
        # self.toolBar.show()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AIMat", None))
        MainWindow.setWindowIcon(QtGui.QIcon('images/AIMat.jpg'))
        self.QuitBtn.setText(_translate("MainWindow", "Quit", None))
        # self.antImg.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Images/resized_img.png\"/></p></body></html>", None))
        self.antImg.setPixmap(QtGui.QPixmap("images/resized_img.png"))
        self.antImg.show()
        self.comboBox1.setItemText(0, _translate("MainWindow", "Select a Material", None))
        self.comboBox1.setItemText(1, _translate("MainWindow", "Bi2O3", None))
        self.comboBox1.setItemText(2, _translate("MainWindow", "SiO2", None))
        self.comboBox1.setItemText(3, _translate("MainWindow", "TiO2", None))
        self.comboBox1.setItemText(4, _translate("MainWindow", "Mg2B2O5", None))
        self.comboBox1.setItemText(5, _translate("MainWindow", "Mg2SiO4", None))
        self.comboBox1.setItemText(6, _translate("MainWindow", "CaSiO3", None))
        self.comboBox1.setItemText(7, _translate("MainWindow", "Zn2SiO4", None))
        self.comboBox1.setItemText(8, _translate("MainWindow", "LiF", None))
        self.comboBox1.setItemText(9, _translate("MainWindow", "CaMg0.9Zn0.1Si2O6", None))
        self.comboBox1.setItemText(10, _translate("MainWindow", "MgF2", None))
        self.comboBox1.setItemText(11, _translate("MainWindow", "LiMgPO4", None))
        self.comboBox1.setItemText(12, _translate("MainWindow", "CaAl2Si2O8", None))
        self.comboBox1.setItemText(13, _translate("MainWindow", "LiMg0.9Zn0.1PO4", None))
        self.comboBox1.setItemText(14, _translate("MainWindow", "(Mg0.4Zn0.6)2SiO4", None))
        self.comboBox1.setItemText(15, _translate("MainWindow", "CaTiO3", None))
        self.comboBox1.setItemText(16, _translate("MainWindow", "Sr2Al2SiO7", None))
        self.comboBox1.setItemText(17, _translate("MainWindow", "Sr2ZnSi2O7", None))
        self.comboBox1.setItemText(18, _translate("MainWindow", "SrTiO3", None))
        self.comboBox1.setItemText(19, _translate("MainWindow", "MgAl2O4", None))
        self.comboBox1.setItemText(20, _translate("MainWindow", "ZnAl2O4", None))
        self.comboBox1.setItemText(21, _translate("MainWindow", "Mg2TiO4", None))
        self.comboBox1.setItemText(22, _translate("MainWindow", "LiMg0.95Ni0.05PO4", None))
        self.comboBox1.setItemText(23, _translate("MainWindow", "Al2O3", None))
        self.comboBox1.setItemText(24, _translate("MainWindow", "LiMg0.95Co0.05PO4", None))
        self.comboBox1.setItemText(25, _translate("MainWindow", "Li2WO4", None))
        self.comboBox1.setItemText(26, _translate("MainWindow", "Y3Al5O12", None))
        self.comboBox1.setItemText(27, _translate("MainWindow", "BaMoO4", None))
        self.comboBox1.setItemText(28, _translate("MainWindow", "Li2MoO4", None))
        self.comboBox1.setItemText(29, _translate("MainWindow", "SrMoO4", None))
        self.comboBox1.setItemText(30, _translate("MainWindow", "NaCa2Mg2V3O12", None))
        self.comboBox1.setItemText(31, _translate("MainWindow", "BaWO4", None))
        self.comboBox1.setItemText(32, _translate("MainWindow", "LiYW2O8", None))
        self.comboBox1.setItemText(33, _translate("MainWindow", "LiCa3MgV3O12", None))
        self.comboBox1.setItemText(34, _translate("MainWindow", "CaMoO4", None))
        self.comboBox1.setItemText(35, _translate("MainWindow", "BaTa2P2O11", None))
        self.comboBox1.setItemText(36, _translate("MainWindow", "(Al1/2Ta1/2)O2", None))
        self.comboBox1.setItemText(37, _translate("MainWindow", "(Mg1/3Ta2/3)O2", None))
        self.comboBox1.setItemText(38, _translate("MainWindow", "CeO2", None))
        self.comboBox1.setItemText(39, _translate("MainWindow", "ZnWO4", None))
        self.comboBox1.setItemText(40, _translate("MainWindow", "(Li1/2Nd1/2)WO4", None))
        self.comboBox1.setItemText(41, _translate("MainWindow", "MgWO4", None))
        self.comboBox1.setItemText(42, _translate("MainWindow", "Ba2BiV3O11", None))
        self.comboBox1.setItemText(43, _translate("MainWindow", "Sm2O3", None))
        self.comboBox1.setItemText(44, _translate("MainWindow", "Ba5Nb4O15", None))
        self.comboBox1.setItemText(45, _translate("MainWindow", "CaWO4", None))
        self.comboBox1.setItemText(46, _translate("MainWindow", "(Mg0.97Zn0.03)(Ti0.95Sn0.05)O4", None))
        self.comboBox1.setItemText(47, _translate("MainWindow", "MgNb2O6", None))
        self.comboBox1.setItemText(48, _translate("MainWindow", "Li3Bi2P3O12", None))
        self.comboBox1.setItemText(49, _translate("MainWindow", "Zn2Te3O8", None))
        self.comboBox1.setItemText(50, _translate("MainWindow", "CaNb2O6", None))
        self.comboBox1.setItemText(51, _translate("MainWindow", "MgTiO3", None))
        self.comboBox1.setItemText(52, _translate("MainWindow", "CaF2", None))
        self.comboBox1.setItemText(53, _translate("MainWindow", "NdNbO4", None))
        self.comboBox1.setItemText(54, _translate("MainWindow", "Mg(Zr0.05Ti0.95)O3", None))
        self.comboBox1.setItemText(55, _translate("MainWindow", "(Mg0.95Co0.05)TiO3", None))
        self.comboBox1.setItemText(56, _translate("MainWindow", "BaCu(B2O5)", None))
        self.comboBox1.setItemText(57, _translate("MainWindow", "CoLi2/3Ti4/3O4", None))
        self.comboBox1.setItemText(58, _translate("MainWindow", "SrLa4Si3O13", None))
        self.comboBox1.setItemText(59, _translate("MainWindow", "BiSbO4", None))
        self.comboBox1.setItemText(60, _translate("MainWindow", "Li3NbO4", None))
        self.comboBox1.setItemText(61, _translate("MainWindow", "ZnNb2O6", None))
        self.comboBox1.setItemText(62, _translate("MainWindow", "MgLi2/3Ti4/3O4", None))
        self.comboBox1.setItemText(63, _translate("MainWindow", "(Mg0.95Zn0.05)TiO3", None))
        self.comboBox1.setItemText(64, _translate("MainWindow", "CeTe2O6", None))
        self.comboBox1.setItemText(65, _translate("MainWindow", "CoNb2O6", None))
        self.comboBox1.setItemText(66, _translate("MainWindow", "La2/3(Mg1/2W1/2)O3", None))
        self.comboBox1.setItemText(67, _translate("MainWindow", "Bi2Mo2O9", None))
        self.comboBox1.setItemText(68, _translate("MainWindow", "LaAlO3", None))
        self.comboBox1.setItemText(69, _translate("MainWindow", "TeO2", None))
        self.comboBox1.setItemText(70, _translate("MainWindow", "Sr(In1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(71, _translate("MainWindow", "Li2ZnTi3O8", None))
        self.comboBox1.setItemText(72, _translate("MainWindow", "La(Mg1/2Ti1/2)O3", None))
        self.comboBox1.setItemText(73, _translate("MainWindow", "Ba(Mg1/3Ta2/3)O3", None))
        self.comboBox1.setItemText(74, _translate("MainWindow", "Ba(Co1/3Nb2/3)O3", None))
        self.comboBox1.setItemText(75, _translate("MainWindow", "ZnTiO3", None))
        self.comboBox1.setItemText(76, _translate("MainWindow", "Ca(Yb1/2Ta1/2)O3", None))
        self.comboBox1.setItemText(77, _translate("MainWindow", "ZnZrNb2O8", None))
        self.comboBox1.setItemText(78, _translate("MainWindow", "Nd(Co1/2Ti1/2)O3", None))
        self.comboBox1.setItemText(79, _translate("MainWindow", "Sm(Mg1/2Ti1/2)O3", None))
        self.comboBox1.setItemText(80, _translate("MainWindow", "LiBiW2O8", None))
        self.comboBox1.setItemText(81, _translate("MainWindow", "Sr(Yb1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(82, _translate("MainWindow", "BaTi4O9", None))
        self.comboBox1.setItemText(83, _translate("MainWindow", "Ba(Zn1/3Ta2/3)O3", None))
        self.comboBox1.setItemText(84, _translate("MainWindow", "Sr(Sm1/2Ta1/2)O3", None))
        self.comboBox1.setItemText(85, _translate("MainWindow", "Sr(Er1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(86, _translate("MainWindow", "Sr(Y1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(87, _translate("MainWindow", "Sr(Ho1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(88, _translate("MainWindow", "Sr(Dy1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(89, _translate("MainWindow", "Sr(Tb1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(90, _translate("MainWindow", "Ba(Y1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(91, _translate("MainWindow", "Ba(Yb1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(92, _translate("MainWindow", "Ca(Y1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(93, _translate("MainWindow", "BaZn2Ti4O11", None))
        self.comboBox1.setItemText(94, _translate("MainWindow", "Sr(Gd1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(95, _translate("MainWindow", "Sr(Eu1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(96, _translate("MainWindow", "Zn3Nb2O8", None))
        self.comboBox1.setItemText(97, _translate("MainWindow", "Ca(Mg1/3Nb2/3)O3", None))
        self.comboBox1.setItemText(98, _translate("MainWindow", "Sr(Nd1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(99, _translate("MainWindow", "Sm(Co1/2Ti1/2)O3", None))
        self.comboBox1.setItemText(100, _translate("MainWindow", "NdAlO3", None))
        self.comboBox1.setItemText(101, _translate("MainWindow", "Ca5Ta2TiO12", None))
        self.comboBox1.setItemText(102, _translate("MainWindow", "SmAlO3", None))
        self.comboBox1.setItemText(103, _translate("MainWindow", "CaTi0.4(Al1/2Nb1/2).6O3", None))
        self.comboBox1.setItemText(104, _translate("MainWindow", "Nd(Mg1/2Ti1/2)O3", None))
        self.comboBox1.setItemText(105, _translate("MainWindow", "Ca4La2Ti5O17", None))
        self.comboBox1.setItemText(106, _translate("MainWindow", "ZrTiO4", None))
        self.comboBox1.setItemText(107, _translate("MainWindow", "NiNb2O6", None))
        self.comboBox1.setItemText(108, _translate("MainWindow", "Nd3Ga5O12", None))
        self.comboBox1.setItemText(109, _translate("MainWindow", "LaGaO3", None))
        self.comboBox1.setItemText(110, _translate("MainWindow", "Ca(Mg1/3Ta2/3)O3", None))
        self.comboBox1.setItemText(111, _translate("MainWindow", "LiNb3O8", None))
        self.comboBox1.setItemText(112, _translate("MainWindow", "ZnTa2O6", None))
        self.comboBox1.setItemText(113, _translate("MainWindow", "Ca5Nb2TiO12", None))
        self.comboBox1.setItemText(114, _translate("MainWindow", "CaTi0.5(Al1/2Nb1/2).5O3", None))
        self.comboBox1.setItemText(115, _translate("MainWindow", "La(Zn1/2Ti1/2)O3", None))
        self.comboBox1.setItemText(116, _translate("MainWindow", "TiFeNbO6", None))
        self.comboBox1.setItemText(117, _translate("MainWindow", "(La1/2Na1/2)TiO3", None))
        self.comboBox1.setItemText(118, _translate("MainWindow", "Nd(Zn1/2Ti1/2)O3", None))
        self.comboBox1.setItemText(119, _translate("MainWindow", "Ba(Ti0.85Mn0.15)O3", None))
        self.comboBox1.setItemText(120, _translate("MainWindow", "CaTi.6(Al1/2Nb1/2).4O3", None))
        self.comboBox1.setItemText(121, _translate("MainWindow", "Ca(Fe1/2Nb1/2)O3", None))
        self.comboBox1.setItemText(122, _translate("MainWindow", "Ba4Nd9.33Ti18O54", None))
        self.comboBox1.setItemText(123, _translate("MainWindow", "Bi2Ti4O11", None))
        self.comboBox1.setItemText(124, _translate("MainWindow", "Ba4.2Sm9.2Ti18O54", None))
        self.comboBox1.setItemText(125, _translate("MainWindow", "Ba4Sm9.33Ti18O54", None))
        self.comboBox1.setItemText(126, _translate("MainWindow", "Li1/2Nd1/2TiO3", None))
        self.comboBox1.setItemText(127, _translate("MainWindow", "Ca0.6La0.2667TiO3", None))
        self.comboBox1.setItemText(128, _translate("MainWindow", "MgCo2(VO4)2", None))
        self.comboBox1.setItemText(129, _translate("MainWindow", "(Mg.95Co.05)TiO3", None))
        self.comboBox1.setItemText(130, _translate("MainWindow", "Ba(Zn1/3Nb2/3)O3", None))
        self.comboBox1.setItemText(131, _translate("MainWindow", "BaZrO3", None))
        self.comboBox1.setItemText(132, _translate("MainWindow", "Ba(Y1/2Ta1/2)O3", None))
        self.comboBox1.setItemText(133, _translate("MainWindow", "Ba(Ca1/9Y3/9Ta5/9)O3", None))
        self.comboBox1.setItemText(134, _translate("MainWindow", "LiCa3MgV3O12", None))
        self.comboBox1.setItemText(135, _translate("MainWindow", "LiCa3ZnV3O12", None))
        self.comboBox1.setItemText(136, _translate("MainWindow", "LiAlSiO4", None))
        self.comboBox1.activated[str].connect(self.fill_properties1)

        self.comboBox2.setItemText(0, _translate("MainWindow", "Select a Material", None))
        self.comboBox2.setItemText(1, _translate("MainWindow", "Bi2O3", None))
        self.comboBox2.setItemText(2, _translate("MainWindow", "SiO2", None))
        self.comboBox2.setItemText(3, _translate("MainWindow", "TiO2", None))
        self.comboBox2.setItemText(4, _translate("MainWindow", "Mg2B2O5", None))
        self.comboBox2.setItemText(5, _translate("MainWindow", "Mg2SiO4", None))
        self.comboBox2.setItemText(6, _translate("MainWindow", "CaSiO3", None))
        self.comboBox2.setItemText(7, _translate("MainWindow", "Zn2SiO4", None))
        self.comboBox2.setItemText(8, _translate("MainWindow", "LiF", None))
        self.comboBox2.setItemText(9, _translate("MainWindow", "CaMg0.9Zn0.1Si2O6", None))
        self.comboBox2.setItemText(10, _translate("MainWindow", "MgF2", None))
        self.comboBox2.setItemText(11, _translate("MainWindow", "LiMgPO4", None))
        self.comboBox2.setItemText(12, _translate("MainWindow", "CaAl2Si2O8", None))
        self.comboBox2.setItemText(13, _translate("MainWindow", "LiMg0.9Zn0.1PO4", None))
        self.comboBox2.setItemText(14, _translate("MainWindow", "(Mg0.4Zn0.6)2SiO4", None))
        self.comboBox2.setItemText(15, _translate("MainWindow", "CaTiO3", None))
        self.comboBox2.setItemText(16, _translate("MainWindow", "Sr2Al2SiO7", None))
        self.comboBox2.setItemText(17, _translate("MainWindow", "Sr2ZnSi2O7", None))
        self.comboBox2.setItemText(18, _translate("MainWindow", "SrTiO3", None))
        self.comboBox2.setItemText(19, _translate("MainWindow", "MgAl2O4", None))
        self.comboBox2.setItemText(20, _translate("MainWindow", "ZnAl2O4", None))
        self.comboBox2.setItemText(21, _translate("MainWindow", "Mg2TiO4", None))
        self.comboBox2.setItemText(22, _translate("MainWindow", "LiMg0.95Ni0.05PO4", None))
        self.comboBox2.setItemText(23, _translate("MainWindow", "Al2O3", None))
        self.comboBox2.setItemText(24, _translate("MainWindow", "LiMg0.95Co0.05PO4", None))
        self.comboBox2.setItemText(25, _translate("MainWindow", "Li2WO4", None))
        self.comboBox2.setItemText(26, _translate("MainWindow", "Y3Al5O12", None))
        self.comboBox2.setItemText(27, _translate("MainWindow", "BaMoO4", None))
        self.comboBox2.setItemText(28, _translate("MainWindow", "Li2MoO4", None))
        self.comboBox2.setItemText(29, _translate("MainWindow", "SrMoO4", None))
        self.comboBox2.setItemText(30, _translate("MainWindow", "NaCa2Mg2V3O12", None))
        self.comboBox2.setItemText(31, _translate("MainWindow", "BaWO4", None))
        self.comboBox2.setItemText(32, _translate("MainWindow", "LiYW2O8", None))
        self.comboBox2.setItemText(33, _translate("MainWindow", "LiCa3MgV3O12", None))
        self.comboBox2.setItemText(34, _translate("MainWindow", "CaMoO4", None))
        self.comboBox2.setItemText(35, _translate("MainWindow", "BaTa2P2O11", None))
        self.comboBox2.setItemText(36, _translate("MainWindow", "(Al1/2Ta1/2)O2", None))
        self.comboBox2.setItemText(37, _translate("MainWindow", "(Mg1/3Ta2/3)O2", None))
        self.comboBox2.setItemText(38, _translate("MainWindow", "CeO2", None))
        self.comboBox2.setItemText(39, _translate("MainWindow", "ZnWO4", None))
        self.comboBox2.setItemText(40, _translate("MainWindow", "(Li1/2Nd1/2)WO4", None))
        self.comboBox2.setItemText(41, _translate("MainWindow", "MgWO4", None))
        self.comboBox2.setItemText(42, _translate("MainWindow", "Ba2BiV3O11", None))
        self.comboBox2.setItemText(43, _translate("MainWindow", "Sm2O3", None))
        self.comboBox2.setItemText(44, _translate("MainWindow", "Ba5Nb4O15", None))
        self.comboBox2.setItemText(45, _translate("MainWindow", "CaWO4", None))
        self.comboBox2.setItemText(46, _translate("MainWindow", "(Mg0.97Zn0.03)(Ti0.95Sn0.05)O4", None))
        self.comboBox2.setItemText(47, _translate("MainWindow", "MgNb2O6", None))
        self.comboBox2.setItemText(48, _translate("MainWindow", "Li3Bi2P3O12", None))
        self.comboBox2.setItemText(49, _translate("MainWindow", "Zn2Te3O8", None))
        self.comboBox2.setItemText(50, _translate("MainWindow", "CaNb2O6", None))
        self.comboBox2.setItemText(51, _translate("MainWindow", "MgTiO3", None))
        self.comboBox2.setItemText(52, _translate("MainWindow", "CaF2", None))
        self.comboBox2.setItemText(53, _translate("MainWindow", "NdNbO4", None))
        self.comboBox2.setItemText(54, _translate("MainWindow", "Mg(Zr0.05Ti0.95)O3", None))
        self.comboBox2.setItemText(55, _translate("MainWindow", "(Mg0.95Co0.05)TiO3", None))
        self.comboBox2.setItemText(56, _translate("MainWindow", "BaCu(B2O5)", None))
        self.comboBox2.setItemText(57, _translate("MainWindow", "CoLi2/3Ti4/3O4", None))
        self.comboBox2.setItemText(58, _translate("MainWindow", "SrLa4Si3O13", None))
        self.comboBox2.setItemText(59, _translate("MainWindow", "BiSbO4", None))
        self.comboBox2.setItemText(60, _translate("MainWindow", "Li3NbO4", None))
        self.comboBox2.setItemText(61, _translate("MainWindow", "ZnNb2O6", None))
        self.comboBox2.setItemText(62, _translate("MainWindow", "MgLi2/3Ti4/3O4", None))
        self.comboBox2.setItemText(63, _translate("MainWindow", "(Mg0.95Zn0.05)TiO3", None))
        self.comboBox2.setItemText(64, _translate("MainWindow", "CeTe2O6", None))
        self.comboBox2.setItemText(65, _translate("MainWindow", "CoNb2O6", None))
        self.comboBox2.setItemText(66, _translate("MainWindow", "La2/3(Mg1/2W1/2)O3", None))
        self.comboBox2.setItemText(67, _translate("MainWindow", "Bi2Mo2O9", None))
        self.comboBox2.setItemText(68, _translate("MainWindow", "LaAlO3", None))
        self.comboBox2.setItemText(69, _translate("MainWindow", "TeO2", None))
        self.comboBox2.setItemText(70, _translate("MainWindow", "Sr(In1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(71, _translate("MainWindow", "Li2ZnTi3O8", None))
        self.comboBox2.setItemText(72, _translate("MainWindow", "La(Mg1/2Ti1/2)O3", None))
        self.comboBox2.setItemText(73, _translate("MainWindow", "Ba(Mg1/3Ta2/3)O3", None))
        self.comboBox2.setItemText(74, _translate("MainWindow", "Ba(Co1/3Nb2/3)O3", None))
        self.comboBox2.setItemText(75, _translate("MainWindow", "ZnTiO3", None))
        self.comboBox2.setItemText(76, _translate("MainWindow", "Ca(Yb1/2Ta1/2)O3", None))
        self.comboBox2.setItemText(77, _translate("MainWindow", "ZnZrNb2O8", None))
        self.comboBox2.setItemText(78, _translate("MainWindow", "Nd(Co1/2Ti1/2)O3", None))
        self.comboBox2.setItemText(79, _translate("MainWindow", "Sm(Mg1/2Ti1/2)O3", None))
        self.comboBox2.setItemText(80, _translate("MainWindow", "LiBiW2O8", None))
        self.comboBox2.setItemText(81, _translate("MainWindow", "Sr(Yb1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(82, _translate("MainWindow", "BaTi4O9", None))
        self.comboBox2.setItemText(83, _translate("MainWindow", "Ba(Zn1/3Ta2/3)O3", None))
        self.comboBox2.setItemText(84, _translate("MainWindow", "Sr(Sm1/2Ta1/2)O3", None))
        self.comboBox2.setItemText(85, _translate("MainWindow", "Sr(Er1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(86, _translate("MainWindow", "Sr(Y1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(87, _translate("MainWindow", "Sr(Ho1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(88, _translate("MainWindow", "Sr(Dy1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(89, _translate("MainWindow", "Sr(Tb1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(90, _translate("MainWindow", "Ba(Y1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(91, _translate("MainWindow", "Ba(Yb1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(92, _translate("MainWindow", "Ca(Y1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(93, _translate("MainWindow", "BaZn2Ti4O11", None))
        self.comboBox2.setItemText(94, _translate("MainWindow", "Sr(Gd1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(95, _translate("MainWindow", "Sr(Eu1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(96, _translate("MainWindow", "Zn3Nb2O8", None))
        self.comboBox2.setItemText(97, _translate("MainWindow", "Ca(Mg1/3Nb2/3)O3", None))
        self.comboBox2.setItemText(98, _translate("MainWindow", "Sr(Nd1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(99, _translate("MainWindow", "Sm(Co1/2Ti1/2)O3", None))
        self.comboBox2.setItemText(100, _translate("MainWindow", "NdAlO3", None))
        self.comboBox2.setItemText(101, _translate("MainWindow", "Ca5Ta2TiO12", None))
        self.comboBox2.setItemText(102, _translate("MainWindow", "SmAlO3", None))
        self.comboBox2.setItemText(103, _translate("MainWindow", "CaTi0.4(Al1/2Nb1/2).6O3", None))
        self.comboBox2.setItemText(104, _translate("MainWindow", "Nd(Mg1/2Ti1/2)O3", None))
        self.comboBox2.setItemText(105, _translate("MainWindow", "Ca4La2Ti5O17", None))
        self.comboBox2.setItemText(106, _translate("MainWindow", "ZrTiO4", None))
        self.comboBox2.setItemText(107, _translate("MainWindow", "NiNb2O6", None))
        self.comboBox2.setItemText(108, _translate("MainWindow", "Nd3Ga5O12", None))
        self.comboBox2.setItemText(109, _translate("MainWindow", "LaGaO3", None))
        self.comboBox2.setItemText(110, _translate("MainWindow", "Ca(Mg1/3Ta2/3)O3", None))
        self.comboBox2.setItemText(111, _translate("MainWindow", "LiNb3O8", None))
        self.comboBox2.setItemText(112, _translate("MainWindow", "ZnTa2O6", None))
        self.comboBox2.setItemText(113, _translate("MainWindow", "Ca5Nb2TiO12", None))
        self.comboBox2.setItemText(114, _translate("MainWindow", "CaTi0.5(Al1/2Nb1/2).5O3", None))
        self.comboBox2.setItemText(115, _translate("MainWindow", "La(Zn1/2Ti1/2)O3", None))
        self.comboBox2.setItemText(116, _translate("MainWindow", "TiFeNbO6", None))
        self.comboBox2.setItemText(117, _translate("MainWindow", "(La1/2Na1/2)TiO3", None))
        self.comboBox2.setItemText(118, _translate("MainWindow", "Nd(Zn1/2Ti1/2)O3", None))
        self.comboBox2.setItemText(119, _translate("MainWindow", "Ba(Ti0.85Mn0.15)O3", None))
        self.comboBox2.setItemText(120, _translate("MainWindow", "CaTi.6(Al1/2Nb1/2).4O3", None))
        self.comboBox2.setItemText(121, _translate("MainWindow", "Ca(Fe1/2Nb1/2)O3", None))
        self.comboBox2.setItemText(122, _translate("MainWindow", "Ba4Nd9.33Ti18O54", None))
        self.comboBox2.setItemText(123, _translate("MainWindow", "Bi2Ti4O11", None))
        self.comboBox2.setItemText(124, _translate("MainWindow", "Ba4.2Sm9.2Ti18O54", None))
        self.comboBox2.setItemText(125, _translate("MainWindow", "Ba4Sm9.33Ti18O54", None))
        self.comboBox2.setItemText(126, _translate("MainWindow", "Li1/2Nd1/2TiO3", None))
        self.comboBox2.setItemText(127, _translate("MainWindow", "Ca0.6La0.2667TiO3", None))
        self.comboBox2.setItemText(128, _translate("MainWindow", "MgCo2(VO4)2", None))
        self.comboBox2.setItemText(129, _translate("MainWindow", "(Mg.95Co.05)TiO3", None))
        self.comboBox2.setItemText(130, _translate("MainWindow", "Ba(Zn1/3Nb2/3)O3", None))
        self.comboBox2.setItemText(131, _translate("MainWindow", "BaZrO3", None))
        self.comboBox2.setItemText(132, _translate("MainWindow", "Ba(Y1/2Ta1/2)O3", None))
        self.comboBox2.setItemText(133, _translate("MainWindow", "Ba(Ca1/9Y3/9Ta5/9)O3", None))
        self.comboBox2.setItemText(134, _translate("MainWindow", "LiCa3MgV3O12", None))
        self.comboBox2.setItemText(135, _translate("MainWindow", "LiCa3ZnV3O12", None))
        self.comboBox2.setItemText(136, _translate("MainWindow", "LiAlSiO4", None))
        # self.comboBox2.model().sort(0)
        self.comboBox2.activated[str].connect(self.fill_properties2)

        self.CompLbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Composition Format : (1 - x)A - xB </span></p></body></html>", None))
        self.Mat1Lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Constituent Material 1 :</span></p></body></html>", None))
        self.Mat2Lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Constituent Material 2 :</span></p></body></html>", None))
        self.MolarFracLbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Molar Fraction (x) :</span></p></body></html>", None))

        # self.aimatImg.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Images/resized_aimat.png\"/></p></body></html>", None))
        self.aimatImg.setPixmap(QtGui.QPixmap("images/resized_aimat.png"))
        self.aimatImg.show()
        self.diConstLbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Dielectric Constant</span></p></body></html>", None))
        self.QfLbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Q*f (GHz)</span></p></body></html>", None))
        self.TcfLbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Tcf (ppm/</span><span style=\" font-weight:600; vertical-align:super;\">0</span><span style=\" font-weight:600;\">C)</span></p></body></html>", None))
        self.predictionsLbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">AI Predicted Properties :</span></p></body></html>", None))
        self.calculateBtn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.calculateBtn.setText(_translate("MainWindow", "Calculate", None))
        self.sintLbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">AI Predicted<br/>Sintering Temperature (</span><span style=\" font-size:14pt; font-weight:600; vertical-align:super;\">0</span><span style=\" font-size:14pt; font-weight:600;\">C)</span></p></body></html>", None))
        self.colon.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">:</span></p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menuView.setTitle(_translate("MainWindow", "&View", None))
        self.menuWindow.setTitle(_translate("MainWindow", "&Window", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete", None))
        self.actionReset_All.setText(_translate("MainWindow", "Reset All", None))
        self.actionView_Database.setText(_translate("MainWindow", "View Database", None))
        self.actionAI_Model.setText(_translate("MainWindow", "AI Model", None))
        self.actionPlot.setText(_translate("MainWindow", "Plot", None))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize", None))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize", None))
        self.actionDocumentation.setText(_translate("MainWindow", "&Documentation", None))
        self.actionSupport.setText(_translate("MainWindow", "&Support", None))
        # self.closeAction.setText(_translate("MainWindow", "&Close", None))
        # self.show()

    # def home(self):



    def new_application(self):
        pass

    def open_application(self):
        pass

    def save_application(self):
        if not self.saved_once:
            self.save_name = QtGui.QFileDialog.getSaveFileName(self, 'Save File')
            file = open(self.save_name , 'w')
            self.saved_once = 1
        else:
            file = open(self.save_name, 'a')
        material1 = self.comboBox1.currentText()
        material2 = self.comboBox2.currentText()
        n2 = self.molarFrac.toPlainText()
        n1 = str(1 - float(n2))
        dipred = self.diConstPred.toPlainText()
        qfpred = self.QfPred.toPlainText()
        tcfpred = self.TcfPred.toPlainText()

        file.write(n1+material1+' - '+ n2+material2+ ','+ dipred+','+qfpred+','+tcfpred+'\n')
        file.close()
        

    def save_as_application(self):
        pass

    def quit_application(self):
        choice = QtGui.QMessageBox.question(MainWindow, 'Quit', 'Are you sure you want to quit?', 
                                                            QtGui.QMessageBox.Yes, QtGui.QMessageBox.No)
        if choice == QtGui.QMessageBox.Yes: sys.exit()
        else: pass

    def undo_application(self):
        pass

    def redo_application(self):
        pass

    def cut_application(self):
        pass

    def copy_application(self):
        pass

    def paste_application(self):
        pass

    def delete_application(self):
        pass

    def reset_application(self):
        #resetting all text boxes to None
        self.diConst1.clear()
        self.Qf1.clear()
        self.Tcf1.clear()
        self.diConst2.clear()
        self.Qf2.clear()
        self.Tcf2.clear()
        self.molarFrac.clear()
        self.diConstPred.clear()
        self.QfPred.clear()
        self.TcfPred.clear()
        self.sintPred.clear()

        #resetting combo boxes
        self.comboBox1.setCurrentIndex(0)
        self.comboBox2.setCurrentIndex(0)

    def view_database_application(self):
        pass

    def aimodel_application(self):
        pass

    def plot_application(self):
        pass

    def minimize_application(self):
        pass

    def maximize_application(self):
        pass

    def documentation_application(self):
        pass

    def support_application(self):
        pass

    def fill_properties1(self):
        #get the current text in the combo boxes
        if self.comboBox1.currentIndex() >0:
            self.mat1 = unicode(self.comboBox1.currentText())
        else:   #if nothing is selected pop up warning message
            self.no_data_msg.exec_()
        #get the properties of selected materials
        self.mat1_prop = SC_DF.loc[SC_DF['Material'] == self.mat1]

        self.er1, self.qf1, self.tcf1 = self.mat1_prop.iloc[0]['er'], self.mat1_prop.iloc[0]['Qf'], self.mat1_prop.iloc[0]['Tcf']
        
        #make the properties to strings
        str_er1, str_qf1, str_tcf1 = '{0:0.2f}'.format(self.er1), '{0:d}'.format(self.qf1), '{0:0.2f}'.format(self.tcf1) 
        
        #show the properties in the text boxes
        self.diConst1.setText(str_er1)
        self.Qf1.setText(str_qf1)
        self.Tcf1.setText(str_tcf1)

    def fill_properties2(self):
        #get the current text in the combo boxes
        if self.comboBox2.currentIndex() >0:
            self.mat2 = unicode(self.comboBox2.currentText())
        else:   #if nothing is selected pop up warning message
            self.no_data_msg.exec_()
        
        #get the properties of selected materials
        self.mat2_prop = SC_DF.loc[SC_DF['Material'] == self.mat2]

        self.er2, self.qf2, self.tcf2 = self.mat2_prop.iloc[0]['er'], self.mat2_prop.iloc[0]['Qf'], self.mat2_prop.iloc[0]['Tcf']
        
        #make the properties to strings
        str_er2, str_qf2, str_tcf2 = '{0:0.2f}'.format(self.er2), '{0:d}'.format(self.qf2), '{0:0.2f}'.format(self.tcf2) 
        
        #show the properties in the text boxes
        self.diConst2.setText(str_er2)
        self.Qf2.setText(str_qf2)
        self.Tcf2.setText(str_tcf2)

    def calculate(self):

        #check if all the required fields are filled
        if (self.comboBox1.currentIndex()==0 or self.comboBox2.currentIndex()==0 or self.molarFrac.toPlainText()==''):
            self.no_data_msg = QMessageBox()
            self.no_data_msg.setIcon(QMessageBox.Warning)
            self.no_data_msg.setWindowTitle("Enter Data")
            self.no_data_msg.setText('Please fill all the required fields!')
            self.no_data_msg.exec_()

        else:
            # print 'all the calculations happen here'
            self.mol_frac = float(str(self.molarFrac.toPlainText()))

            self.input_df = pd.DataFrame(columns=['er1', 'Qf1', 'Tcf1', 'er2', 'Qf2', 'Tcf2', 'V1', 'V2'], 
                                                data=[[self.er1,self.qf1,self.tcf1,self.er2,self.qf2,self.tcf2, 1.0-self.mol_frac,self.mol_frac]])

            self.pred_er, self.pred_qf, self.pred_tcf = cpm_run.predict_properties(self.input_df)
            # convert floats to strings for displaying
            str_er, str_qf, str_tcf = "{0:.2f}".format(self.pred_er), "{0:.2f}".format(self.pred_qf), "{0:.2f}".format(self.pred_tcf)

            #show the predictions in the appropriate boxes
            self.diConstPred.setText(str_er)
            self.QfPred.setText(str_qf)
            self.TcfPred.setText(str_tcf)

            #Predicting sintering temperature
            self.sint_input_df = pd.DataFrame(columns=['er', 'Qf', 'Tcf'], 
                                                data=[[self.pred_er,self.pred_qf,self.pred_tcf]])
            self.pred_sint = sintering_run.predict_sintering(self.sint_input_df)

            #float to string
            str_sint = "{0:d}".format(int(self.pred_sint))
            #show sintering prediction in the box
            self.sintPred.setText(str_sint)

        # print 'sintering predictions', self.pred_sint

        # print self.input_df

# import app_image_rc



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

